# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20160325_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='publication',
            new_name='published',
        ),
    ]
