# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_auto_20160325_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='author',
        ),
        migrations.AddField(
            model_name='entry',
            name='author',
            field=models.ManyToManyField(to='feeds.Author'),
        ),
    ]
