# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_auto_20160325_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='author',
            new_name='authors',
        ),
    ]
