# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_auto_20160325_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
