# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0010_entry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
