# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0011_auto_20160326_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-published']},
        ),
    ]
