# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0012_auto_20160326_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='entry',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(null=True, upload_to='entry_images/'),
        ),
    ]
