# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0013_auto_20160329_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
